#!/bin/bash

echo -n "파일/디렉토리 이름 입력 [enter] : "
read name

if [ ! -e "$name" ]; then
    echo "$name 은 존재하지 않습니다."
    exit 0
fi

if [ -d "$name" ]; then
    echo "$name 은 디렉토리 입니다."
elif [ -L "$name" ]; then
    echo "$name 은 심볼릭링크 입니다."
elif [ -c "$name" ]; then
    echo "$name 은 문자장치 입니다."
elif [ -b "$name" ]; then
    echo "$name 은 블록장치 입니다."
elif [ -p "$name" ]; then
    echo "$name 은 파이프 입니다."
elif [ -S "$name" ]; then
    echo "$name 은 소켓 입니다."
elif [ -f "$name" ]; then
    echo "$name 은 보통파일 입니다."
fi
